### ISSUE TITLE
Calckey/Misskey support

### ISSUE THREAD

**Issue by ThatOneCalculator** [CyberFurz/furryfediverse-site#23]
API docs: https://i.calckey.cloud/api-doc

JS lib: https://www.npmjs.com/package/calckey-js

**Comment by hack13** [comment]
Thank you, I am looking through the API docs here... I am seeing where I can pull some of the information we collect from... but I am trying to locate 2 pieces I cannot find:

- Instance contact (where/who we can send a DM to verify the adding of the instance is ok'd by the admin of said instance)
- Hero image, otherwise we might just need to do something generic for calckey/misskey instances

**Comment by hack13** [comment]
Ok... nvm I found where to get your banner image... I am still needing a way to get your instance owner/maintaner I see how to get the email... but not their account to DM them.

**Comment by Pokefan5** [comment]
The only endpoint to list admin users requires... admin/moderator credentials

The alternative seems to be to scrape the public user search until you find an admin user

**Comment by hack13** [comment]
We have internally talked about it, and think if your instance is a misskey/calckey it will prompt you to put in your admin username, we will check against the API for "isAdmin" then send the DM to the admin to confirm they have pemrission to add the instance to the list.

**Comment by ineffyble** [comment]
Should possibly also add a Misskey app to the recommended apps section in some form, since unfortunately none of the Mastodon apps have Misskey support.

**Comment by hack13** [comment]
@ineffyble can you please suggest an Android and iOS since I don't have much experience with the Misskey forks.

**Comment by ineffyble** [comment]
@ThatOneCalculator I think I'd defer to you for this, but I know there's not many options at all.

**Comment by ThatOneCalculator** [comment]
For iOS and Android, the most complete option is going to be the PWA (install/add to home screen option on your browser). It has offline support, notifications, etc and acts like a native app. 

For actual native apps, there's a couple choices for Android:

- Milktea (Play store): fairly feature complete, slightly outdated UI, second-class Calckey support, only supports Mk/Ck

- Kaiteki (https://GitHub.com/kaiteki-fedi/kaiteki): still in alpha but adding more features rapidly, beautiful UI, first-class Calckey support, supports almost all fedi platforms as well. This will become my client of choice once it gets more complete. 

- Subway Tooter (Play store, F-Droid): packed with features but the UI is very clunky to navigate, second-class Calckey support, supports Mk/Ck and Masto. 

iOS:

- SocialHub (App Store, $4.99): features unknown but seemingly complete. I don't have an iOS device to test it with. Second-class Calckey support. 

SailfishOS, Linux mobile:

None at the time of writing this.

**Comment by ineffyble** [comment]
I've implemented partial support in https://github.com/ineffyble/transfediverse now but it's very hacky:

Working:
- Submission of "Add Instance" form for Misskey/Calckey
- Showing Misskey/Calckey instances with data pulled from the "meta" endpoint

Not working:
- Automatic verification of Misskey/Calckey (after adding, user gets told to DM the admin account for manual verification)
- Getting user stats for Misskey/Calckey (not provided in "meta" endpoint)
- Intelligent info gathering (right now I just hit /instance and fall back to "meta" if an error. Ideally you'd hit a different endpoint based on software info provided at node info endpoint (which all software exposes the location of at `.well-known/nodeinfo`) , which also provides some missing details such as user stats).

**Comment by hack13** [comment]
Patched, closing
