### ISSUE TITLE
Display in random order

### ISSUE THREAD

**Issue by catgoat** [CyberFurz/furryfediverse-site#29]
Hello!

I think it might be nice to display servers in a random order on each page view — that way people will see a different list and it might help cut down on the first few servers listed getting overloaded/spread out sign ups?

**Comment by Pokefan5** [comment]
I actually quite like this idea, and so does @hack13. We'll be adding this.

**Comment by goatrocks** [comment]
Awesome! Thank you 🙏🏻

**Comment by hack13** [comment]
Closing as this has been patched and applied by @Pokefan5

**Comment by catgoat** [comment]
Fantastic! Thank you for implementing this suggestion!
