### ISSUE TITLE
Recommended apps: Metatext no longer in active development

### ISSUE THREAD

**Issue by SebinNyshkim** [CyberFurz/furryfediverse-site#37]
[Metatext's developer](https://mastodon.social/@metabolist/109422457953717612) on Nov 28, 2022:

> Unfortunately I have to stop actively working on #Metatext for a while due to health issues. I really wish I could implement Mastodon 4 features and squash every bug, but it's not possible for me to do so right now.
>
> I know the app has become important to a lot people, so I'm open to a new maintainer who can carry on its values of privacy and accessibility taking it over if there's interest and a fit. Email info@metabolist.org if you (or your organization) are interested

In light of this announcement by the developer, it might be worth noting for visitors to the site that although the app continues to work, it does not offer any of the new features of current Mastodon instances from 4.0 onwards (most notably editing posts).

I can think of three ways to approach this:

- Add a notice that informs visitors about this?
- Add a note to the button, e.g. "(discontinued)", "(dev on halt)", etc.?
- Remove the button entirely?

If the site makes app recommendations, I feel it should make an effort to recommend apps that are actively being developed and support the full feature set of current Mastodon instances. Links to an unmaintained and outdated app could give visitors the wrong first impression about the advantages Mastodon has to offer over Twitter (seeing as site migration tools are also linked).

**Comment by hack13** [comment]
Thank you for letting me know; two newer ones have been gaining a lot of traction on iOS, but they are both in TestFlight... I think Toot!, the developer, has come back, as I have recently seen a couple of updates.

**Comment by SebinNyshkim** [comment]
The two you could be referring to are [Ivory](https://tapbots.com/ivory/) (from Tapbots, former devs of Tweetbot) and [Ice Cubes](https://github.com/Dimillian/IceCubesApp) (another open source Mastodon client). They got released to the App Store not too long ago.

Another Mastodon client for iOS currently on TestFlight is [Woolly](https://testflight.apple.com/join/2LVAJQTP).

If you let me know what to do about Metatext I can include it in a pull request :)

**Comment by hack13** [comment]
I am actually thinking about the one I have been testing, which is Mammoth by [JPEGuin](https://mastodon.social/@JPEGuin)... however these are more options though. I have test Ivory and it is getting there... but I haven't heard about Ice Cubes or Woolly yet.

**Comment by SebinNyshkim** [comment]
Once the apps leave beta testing I can give them another look and issue another PR. I don't think we should recommend people to sign up for unfinished apps with lots of possible breakage x)

But it still leaves the question: What would you wanna do about Metatext on Furry Fediverse?

**Comment by hack13** [comment]
I will remove it and replace it with Ivory and Ice Cubes, this is on my todo list for today.

**Comment by hack13** [comment]
PR #38 fixed this
