### ISSUE TITLE
Can't edit Admin account for Misskey

### ISSUE THREAD

**Issue by ThatOneCalculator** [CyberFurz/furryfediverse-site#42]
- stop.voring.me (general)
- therian.club (focused)
- furry.band (focused)

**Comment by hack13** [comment]
@ThatOneCalculator I have updated furry.band as they were already in our database, however if you wanna add your instance you can follow the automated adding system. https://furryfediverse.org/add-instance let me know if the automated adding of the instances fails. We cannot just add instances to the system as we want to ensure we have consent of the instance owner.

**Comment by ThatOneCalculator** [comment]
Gotcha. Seems like I can't edit this textbox?

![image](https://user-images.githubusercontent.com/44733677/236717633-8e7046c6-2b72-4b0e-a43a-bc4a79f73b66.png)

**Comment by hack13** [comment]
yike yep you caught an oversight of mine let me fix that real quick

**Comment by hack13** [comment]
@ThatOneCalculator should be patched now, you may need to clear your cache to get the updated page.

**Comment by ThatOneCalculator** [comment]
I got this immediately after hitting "submit"

![image](https://user-images.githubusercontent.com/44733677/236718632-22522779-dd05-44a1-a6f3-1afb53e9bb1f.png)

**Comment by ThatOneCalculator** [comment]
Also, there's a typo. It should be "Administrator", not "Administator".

**Comment by hack13** [comment]
an env variable was off throwing me off... but it should be all fixed and your spelling mistake you noticed fixed please try again I was able to successfully add my test server

**Comment by ThatOneCalculator** [comment]
Just woke up and I got another error ^^;

![Screenshot_20230508-072536.png](https://user-images.githubusercontent.com/44733677/236850151-305c8da4-d715-4867-8a90-28a0b261b137.png)

**Comment by hack13** [comment]
That is because in your screenshot you have "mastodon" as the API selected

**Comment by ThatOneCalculator** [comment]
Ah 🤦
